### ISSUE TITLE
use AndroidKeyStore for store encryption key

### ISSUE THREAD

**Issue by long76** [patrickfav/armadillo#44]

**Comment by patrickfav** [comment]
Hi, maybe you have missed it, but currently it is a design choice to NOT include the AndroidKeyStore system (see README.md)

> Android Keystore System is not used: In my humble opinion, the Android Keystore is the best possible way to secure data on an Android device. Unfortunately, due to the massive fragmentation in the ecosystem properly handling and using the Android Keystore System is not easy and has some major drawbacks. Due to working in a security relevant field I have a lot of experience with this technology, therefore the decision was made to not support it for this implementation i.e. to keep it simple.

In my past professional project we used (due to my input) the Android Keystore extensively; we had very high security requirements (read EMV payments). Unfortunately due to the often poor implementation or very vague API description it was often hard to navigate through the device bugs, to find a solution that works on most every device (btw. we had minSDK 23, so devices where not too old). That is why I ommited it in this project because I don't feel I can support it well with my limited time (and resources).

**Comment by long76** [comment]
i see, thanks

**Comment by privnote42** [comment]
Hey, whats your recommendation?
I am searching something to store my encryption key.
I can't enter the key every time, because i want an automatic sync.

**Comment by patrickfav** [comment]
Just turn off user password.

**Comment by luckycloud-GmbH** [comment]
Yes i know its optional, but i want to encrypt the data.
Do you have a alternative for the Android Keystore for automatic systems, like cloud synchronization?

**Comment by patrickfav** [comment]
The data is encrypted with the fingerprint (and salts) which is unique for every device although not entirely confidential if you have access to that device. Storing/fetching the key from a backend is hard to do correctly and I'd advice against it - in my opinion its hardly any more secure than using the finterprint -> if you want to strengthen the security add more data to the finterprint like a user id, etc.
