### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by iblinov65apps** [patrickfav/armadillo#49]
It's some problems with `private static String getAndroidId(Context context)` on some Oreo and Pie devices: ONEPLUS A6010 (9), Pixel 2 XL (10), Mi A1 (9) (from Crashlytics)
```
java.lang.NullPointerException: provided string must not be null
       at java.util.Objects.requireNonNull + 228(Objects.java:228)
       at at.favre.lib.bytes.Bytes.from + 502(Bytes.java:502)
       at at.favre.lib.bytes.Bytes.from + 480(Bytes.java:480)
       at at.favre.lib.armadillo.EncryptionFingerprintFactory.create + 49(EncryptionFingerprintFactory.java:49)
       at at.favre.lib.armadillo.Armadillo$Builder.encryptionFingerprint + 159(Armadillo.java:159)
       at at.favre.lib.armadillo.Armadillo$Builder.encryptionFingerprint + 111(Armadillo.java:111)
```

Please, fix it, if possible.

**Comment by patrickfav** [comment]
Hi,

It seems `getAndroidId()` returns null on these devices - I am not aware that this is an expected behaviour (or have expirenced this myself, although I'm not actively working on Oreo/Pie devices). I would welcome suggestions why this might be null (lifecycle issue?). Other than that your only course of action is to use a custom `EncryptionFingerprint` with `encryptionFingerprint(EncryptionFingerprint fingerprint)` which ommits the android id.

**Comment by nicolasSchirmer** [comment]
Hey patrick, did you looked into this issue?

Here is a clue for it :)
https://android-developers.googleblog.com/2017/04/changes-to-device-identifiers-in.html

**Comment by patrickfav** [comment]
Hi @nicolasSchirmer 

Thanks for the link! Im totally aware of the new behavior. The problem is, resturning null as ANDROID_ID is not a defined behavior and very probably a Device bug :/

**Comment by patrickfav** [comment]
I've implemented a fallback ANDROID_ID if the one provided by the OS is null. Be aware, that if that behaviour is not deterministic, this may compromise the ability to encrypt/decrypt in the future. If that is the case, your only option is to re-implement `EncryptionFingerprint` and omit this property.
