### ISSUE TITLE
Use Android's Log instead of Timber

### ISSUE THREAD

**Issue by fondesa** [patrickfav/armadillo#55]
This issue is just a proposal.

Depending on Timber has some drawbacks:
1. if an app doesn't use Timber, lint raises a warning for each Android's Log call by default since Timber implemented the lint check `LogNotTimber`
2. it increases the APK size 

The first issue is way more important than the second one.
Also because, if someone enables `isWarningsAsErrors` in the `lintOptions`, every Log's call is marked as an error.

Is it possible to depend on Android's Log instead of Timber?

**Comment by patrickfav** [comment]
Hi,

I agree that might be mildly annoying, however it should be trivial to disable the Timber lint rules (see: https://stackoverflow.com/questions/35750024/gradle-clean-fails-because-of-lint-timber).

The second point might be technically true, but we are talking probably a couple of bytes (Timber is a single about 600 LOC java class) - should make practically no difference whatsoever. If you still are not satisfied, you could maybe force proguard to remove parts of the class.

While nowadays Timber might not be the way to go anymore, it was when this lib was introduced - it has a big advantage however: it is easy for the lib user to decide if they want log from the lib.

So all in all, to be honest I dont see a big need to remove Timber as of now.
